show plugin installation

diff --git a/templates/frontend/gatsby/deploy-gke.yml b/templates/frontend/gatsby/deploy-gke.yml
--- a/templates/frontend/gatsby/deploy-gke.yml
+++ b/templates/frontend/gatsby/deploy-gke.yml
@@ -13,7 +13,7 @@
 
 # add private chart museum
 .gatsbyDeploy-initializeChartMuseum: &gatsbyDeploy-initializeChartMuseum |
-  helm plugin install https://github.com/chartmuseum/helm-push > /dev/null 2>&1
+  helm plugin install https://github.com/chartmuseum/helm-push
   helm repo add \
     --username "${HELM_REPOSITORY_USERNAME}" \
     --password "${HELM_REPOSITORY_PASSWORD}" \
@@ -46,6 +46,7 @@
   if [ -z "${HELM_VALUES_FILE}" ]; then echo "HELM_VALUES_FILE is required"; exit 1; fi
   if [ -z "${IMAGE_NAME}" ]; then echo "IMAGE_NAME is required"; exit 1; fi
   if [ -z "${IMAGE_TAG}" ]; then echo "IMAGE_TAG is required"; exit 1; fi
+  if [ -z "${GCR_DOMAIN}" ]; then echo "GCR_DOMAIN is required"; exit 1; fi
 
 
 .gatsbyDeployGke:
