deploy helm chart

diff --git a/templates/frontend/gatsby/deploy-gke.yml b/templates/frontend/gatsby/deploy-gke.yml
--- a/templates/frontend/gatsby/deploy-gke.yml
+++ b/templates/frontend/gatsby/deploy-gke.yml
@@ -31,6 +31,11 @@
     --project="${GCLOUD_PROJECT_ID}" \
     --zone="${GKE_ZONE}"
 
+# set optional values to default values
+.gatsbyDeploy-setDefaultValues: &gatsbyDeploy-setDefaultValues |
+   if [ -z "${HELM_CHART_VERSION}" ]; then export HELM_CHART_VERSION=""; fi
+   if [ -z "${HELM_FORCE_UPGRADE}" ]; then export HELM_FORCE_UPGRADE="false"; fi
+
 .gatsbyDeploy-validateEnvironmentCommon: &gatsbyDeploy-validateEnvironmentCommon |
   if [ -z "${GCLOUD_SA_KEY}" ]; then echo "GCLOUD_SA_KEY is required"; exit 1; fi
   if [ -z "${GCLOUD_PROJECT_ID}" ]; then echo "GCLOUD_PROJECT_ID is required"; exit 1; fi
@@ -47,13 +52,35 @@
   if [ -z "${HELM_VALUES_FILE}" ]; then echo "HELM_VALUES_FILE is required"; exit 1; fi
   if [ -z "${IMAGE_NAME}" ]; then echo "IMAGE_NAME is required"; exit 1; fi
   if [ -z "${IMAGE_TAG}" ]; then echo "IMAGE_TAG is required"; exit 1; fi
+  if [ -z "${APP_NAME}" ]; then echo "APP_NAME is required"; exit 1; fi
+  if [ -z "${PROJECT_NAME}" ]; then echo "PROJECT_NAME is required"; exit 1; fi
+  if [ -z "${RUNTIME_ENVIRONMENT}" ]; then echo "RUNTIME_ENVIRONMENT is required"; exit 1; fi
 
+.gatsbyDeploy-helmDeploy: &.gatsbyDeploy-helmDeploy |
+  helm upgrade \
+    --install \
+    --set-file "${HELM_VALUES_FILE}" \
+    --set general.imageName="${IMAGE_NAME}" \
+    --set general.imageTag="${IMAGE_TAG}" \
+    --set general.appName="${APP_NAME}" \
+    --set general.projectName="${PROJECT_NAME}" \
+    --set general.environment="${RUNTIME_ENVIRONMENT}" \
+    --set general.meta.buildHash="${CI_COMMIT_SHORT_SHA}" \
+    --set general.meta.branch="${CI_COMMIT_REF_NAME}" \
+    --set general.meta.repositoryUrl="${CI_PROJECT_URL}" \
+    --set general.gcpProjectId="${GCLOUD_PROJECT_ID}" \
+    --version "${HELM_CHART_VERSION}" \
+    --force "${HELM_FORCE_UPGRADE}" \
+    --namespace "${GKE_NAMESPACE}" \
+    "${HELM_RELEASE_NAME}" \
+    "${HELM_CHART_NAME}"
 
 .gatsbyDeployGke:
   stage: deploy
   image: google/cloud-sdk:242.0.0-alpine
   before_script:
     - *gatsbyDeploy-validateEnvironmentCommon
+    - *gatsbyDeploy-setDefaultValues
     - *gatsbyDeploy-installKubectl
     - *gatsbyDeploy-installHelm
     - *gatsbyDeploy-initializeChartMuseum
