add image and tag

diff --git a/templates/frontend/gatsby/deploy-gke.yml b/templates/frontend/gatsby/deploy-gke.yml
--- a/templates/frontend/gatsby/deploy-gke.yml
+++ b/templates/frontend/gatsby/deploy-gke.yml
@@ -43,6 +43,9 @@
   if [ -z "${HELM_RELEASE_NAME}" ]; then echo "HELM_RELEASE_NAME is required"; exit 1; fi
   if [ -z "${HELM_CHART_NAME}" ]; then echo "HELM_CHART_NAME is required"; exit 1; fi
   if [ -z "${HELM_VALUES_FILE}" ]; then echo "HELM_VALUES_FILE is required"; exit 1; fi
+  if [ -z "${IMAGE_NAME}" ]; then echo "IMAGE_NAME is required"; exit 1; fi
+  if [ -z "${IMAGE_TAG}" ]; then echo "IMAGE_TAG is required"; exit 1; fi
+
 
 .gatsbyDeployGke:
   stage: deploy
